//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GammaFour.DeveloperTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GammaFour.DeveloperTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find command .
        /// </summary>
        public static string CommandNotFoundError {
            get {
                return ResourceManager.GetString("CommandNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string CompanyLabel {
            get {
                return ResourceManager.GetString("CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Extensions.
        /// </summary>
        public static string EditorExtensionsTitle {
            get {
                return ResourceManager.GetString("EditorExtensionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Information.
        /// </summary>
        public static string HeaderInformationGroupTitle {
            get {
                return ResourceManager.GetString("HeaderInformationGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a number..
        /// </summary>
        public static string IllegalNumber {
            get {
                return ResourceManager.GetString("IllegalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;summary&gt;
        ///{0}Initializes a new instance of the &lt;see cref=&quot;{1}&quot;/&gt; {2}.
        ///{0}&lt;/summary&gt;
        ///.
        /// </summary>
        public static string InstanceConstructorHeaderTemplate {
            get {
                return ResourceManager.GetString("InstanceConstructorHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;copyright file=&quot;{1}&quot; company=&quot;{2}&quot;&gt;
        ///{0}   {3}
        ///{0}&lt;/copyright&gt;
        ///{0}&lt;author&gt;{4}&lt;/author&gt;
        ///.
        /// </summary>
        public static string ModuleHeaderTemplate {
            get {
                return ResourceManager.GetString("ModuleHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Extensions.
        /// </summary>
        public static string PaneName {
            get {
                return ResourceManager.GetString("PaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;summary&gt;
        ///{0}Initializes static members of the &lt;see cref=&quot;{1}&quot;/&gt; {2}.
        ///{0}&lt;/summary&gt;
        ///.
        /// </summary>
        public static string StaticConstructorHeaderTemplate {
            get {
                return ResourceManager.GetString("StaticConstructorHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap Column.
        /// </summary>
        public static string WordWrapPrompt {
            get {
                return ResourceManager.GetString("WordWrapPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Margin:.
        /// </summary>
        public static string WrapMarginLabel {
            get {
                return ResourceManager.GetString("WrapMarginLabel", resourceCulture);
            }
        }
    }
}
